workflows:
  build_apk:
    name: Build Scribbly Checklist APK
    instance_type: mac_mini  # You can use mac_mini or linux
    max_build_duration: 60
    environment:
      flutter: stable
    scripts:
      - name: Get Flutter packages
        script: flutter pub get
      - name: Build APK
        script: flutter build apk --release
    artifacts:
      - build/app/outputs/flutter-apk/app-release.apk
